### ISSUE TITLE
Proposal: expand presented form to support separate presentation signature

### ISSUE THREAD

**Issue by quartzjer** [json-web-proofs/json-web-proofs#57] opened 2022-06-12 22:26 UTC
I'd like to add another presentation form with five sections:
`<presentation_header>.<issuer_header>.<payload_1>~<payload_2>.<presentation_proof>.<presentation_signature>`

Right now, the SU/MAC algs incorporate the presentation signature into the proof and it doesn't feel right.  The holder should be able to choose their own presentation algorithm independently from the issuer, and it should be able to be any normal JWS one.  

For algorithms such as BBS that internally incorporate replay protection and presentation header support, they would remain four-part but also re-order to be consistent:
`<presentation_header>.<issuer_header>.<payload_1>~<payload_2>.<presentation_proof>`

**Comment by dwaite** [comment] 2024-02-16 23:16
I suspect this is part of a larger conversation about multi-signature/multi-proof structuring and whether that influences compact serialization/JSON serialization. See #50

**Comment by selfissued** [comment] 2024-02-17 22:37
I believe that we need make presentation signatures/proofs independent of the issuer, as @quartzjer suggests.

**Comment by dwaite** [comment] 2024-02-20 22:17
Could use clarity around examples

**Comment by dwaite** [comment] 2024-02-27 23:45
I'm closing this out as a duplicate of #59

**Closed by dwaite** 2024-02-27 23:45 UTC
Labels: JPA, JWP
